import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";
import SmallNavbarFetcher from "@/components/header/SmallNavbarFetcher";
import Modal from "@/components/modal/Modal";
import ModalContextProvider from "@/components/modal/ModalContextProvider";
import { GlobalPageScroller } from "@/components/scrollers/GlobalPageScroller";
import ScrollContextProvider from "@/components/scrollers/ScrollContextProvider";
import "./globals.css";

export const metadata = {
  title: "Younite",
  description: "Generated by create next app",
  icons: {
    icon: "/younitelogo.png",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full overflow-hidden">
      <body className="h-full overflow-hidden">
        {/* Hover to see comments! */}
        <ScrollContextProvider>
          <ModalContextProvider>
            <GlobalPageScroller>
              <div className="invisible sm:visible">
                {/* @ts-ignore is used as a temporary patch for a ts-next incompatibility bug during deployment */}
                {/* @ts-ignore */}
                <Header />
              </div>
              {/* @ts-ignore */}
              <SmallNavbarFetcher />
              <main className="grow overflow-x-hidden">{children}</main>
              <Footer />
            </GlobalPageScroller>
            <Modal />
          </ModalContextProvider>
        </ScrollContextProvider>
      </body>
    </html>
  );
}
