/* eslint-disable @next/next/no-page-custom-font */
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/younitelogo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="bg-gradient-1 z-0 isolate">
        <Header/>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
