# fly.toml app configuration file generated for younite-db-staging on 2024-09-16T21:08:03+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'younite-db-staging'
primary_region = 'syd'

[env]
  PRIMARY_REGION = 'syd'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

[[services.ports]]
  handlers = ["pg_tls"]
  port = 5432

[[services]]
  protocol = 'tcp'
  internal_port = 5433
  auto_start_machines = false

  [[services.ports]]
    port = 5433
    handlers = ['pg_tls']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.pg]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/pg'

  [checks.role]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/role'

  [checks.vm]
    port = 5500
    type = 'http'
    interval = '15s'
    timeout = '10s'
    path = '/flycheck/vm'

[[metrics]]
  port = 9187
  path = '/metrics'
