# fly.toml app configuration file generated for younite on 2024-01-23T20:03:27+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "younite-staging"
primary_region = "syd"

[env]
  STRAPI_URL="https://staging.edit.younite.wdcc.co.nz"

[[vm]]
  memory = "512mb"
  vm = "shared-cpu-4x"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
