# fly.toml app configuration file generated for younite on 2024-01-23T20:03:27+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "younite"
primary_region = "syd"

[[vm]]
  memory = "1gb"
  vm = "performance-1x"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
