runtime: nodejs18

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    script: auto
    secure: always

includes:
  - env_vars.prod.yaml
