# fly.toml app configuration file generated for younite-strapi on 2024-01-17T22:25:22+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "younite-strapi-staging"
primary_region = "syd"

[[vm]]
  size = "shared-cpu-2x"
  memory = "1gb"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
