# fly.toml app configuration file generated for younite-storage on 2024-02-03T16:38:31+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "younite-storage"
primary_region = "syd"
swap_size_mb = 512

[[vm]]
  memory = "512mb"
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="miniodata"
  destination="/data"

[http_service]
  internal_port = 9000
  auto_start_machines=true
  auto_stop_machines='stop'
  min_machines_running = 0