name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy-strapi:
    name: Deploy Strapi Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./strapi
        run: flyctl deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STRAPI_STAGING }}
  deploy-next:
    name: Deploy Next Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./next
        run: flyctl deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile --build-arg STRAPI_KEY=${{ secrets.STAGING_STRAPI_KEY }} --build-arg STRAPI_URL=https://younite-strapi-staging.fly.dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND_STAGING }}
  deploy-storage:
    name: Deploy Storage Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./storage
        run: flyctl deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STORAGE_STAGING }}
