name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-strapi:
    name: Deploy Strapi Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./strapi
        run: flyctl deploy --remote-only --config fly.toml --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STRAPI }}
  deploy-next:
    name: Deploy Next Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./next
        run: flyctl deploy --remote-only --config fly.toml --dockerfile Dockerfile --build-arg STRAPI_KEY=${{ secrets.PRODUCTION_STRAPI_KEY }} --build-arg STRAPI_URL=https://younite-strapi.fly.dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
  deploy-storage:
    name: Deploy Storage Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./storage
        run: flyctl deploy --remote-only --config fly.toml --dockerfile Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STORAGE }}
