name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-strapi:
    name: Deploy Strapi Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd strapi
      - name: Fly Deploy
        working-directory: ./strapi
        run: flyctl deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile.staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STRAPI_STAGING }}
  deploy-frontend:
    name: Deploy Frontend Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd frontend
      - name: Fly Deploy
        working-directory: ./frontend
        run: flyctl deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile.staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND_STAGING }}
  deploy-storage:
    name: Deploy Storage Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd storage
      - name: Fly Deploy
        working-directory: ./storage
        run: flyctl deploy --remote-only --config fly.staging.toml --dockerfile Dockerfile.staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STORAGE_STAGING }}
