name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-strapi:
    name: Deploy Strapi Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config strapi/fly.production.toml --dockerfile strapi/Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STRAPI }}
  deploy-frontend:
    name: Deploy Frontend Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config frontend/fly.production.toml --dockerfile frontend/Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
  deploy-storage:
    name: Deploy Storage Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --config storage/fly.production.toml --dockerfile storage/Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STORAGE }}
