name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-strapi:
    name: Deploy Strapi Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./strapi
        run: flyctl deploy --remote-only --config fly.production.toml --dockerfile Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STRAPI }}
  deploy-frontend:
    name: Deploy Frontend Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./frontend
        run: flyctl deploy --remote-only --config fly.production.toml --dockerfile Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_FRONTEND }}
  deploy-storage:
    name: Deploy Storage Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        working-directory: ./storage
        run: flyctl deploy --remote-only --config fly.production.toml --dockerfile Dockerfile.production
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_STORAGE }}
